config/routes.rb
Rails.application.routes.draw do
  resources :searches do
    collection do
      post :term
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "searches#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/search.rb
class Search < ApplicationRecord
  validates :term, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: %i[ show edit update destroy ]

  # GET /searches or /searches.json
  def index
    @searches = Search.all
  end

  # GET /searches/1 or /searches/1.json
  def show
  end

  # GET /searches/new
  def new
    @search = Search.new
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches or /searches.json
  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to search_url(@search), notice: "Search was successfully created." }
        format.json { render :show, status: :created, location: @search }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searches/1 or /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to search_url(@search), notice: "Search was successfully updated." }
        format.json { render :show, status: :ok, location: @search }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1 or /searches/1.json
  def destroy
    @search.destroy!

    respond_to do |format|
      format.html { redirect_to searches_url, notice: "Search was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # POST /searches/term
  def term
    if params[:term].present?
      @search = Search.where('term LIKE ?', "%#{params[:term]}%")
    else
      @search = []
    end
    params[:term]
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update("search_results", partial: "searches/search_result", locals: { searches: @search })
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def search_params
      params.require(:search).permit(:term)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealtimeFind</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/searches/_form.html.erb
<%= form_with(model: search) do |form| %>
  <% if search.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
        <% search.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :term, style: "display: block" %>
    <%= form.text_field :term %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/searches/_search.html.erb
<div id="<%= dom_id search %>">
  <p>
    <strong>Term:</strong>
    <%= search.term %>
  </p>

</div>

app/views/searches/_search_result.html.erb
<%= @search.count %>
<% searches.each do |search| %>
  <br>
  <%= link_to highlight(search.term, params[:term]), search %>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing search</h1>

<%= render "form", search: @search %>

<br>

<div>
  <%= link_to "Show this search", @search %> |
  <%= link_to "Back to searches", searches_path %>
</div>

app/views/searches/index.html.erb
<% # halt controller that controls form submission after 500ms %>

<h1>Search Here</h1>
<%= form_with url: term_searches_path, method: :post, data: {controller: "halt", halt_target: "form" }  do |form|  %>
  <%= form.search_field :term, data: { action: "input->halt#search" } %>
<%end%>

<div id="search_results">
  search results will go here
</div>

<p style="color: green"><%= notice %></p>



<%= link_to "New search", new_search_path %>

app/views/searches/new.html.erb
<h1>New search</h1>

<%= render "form", search: @search %>

<br>

<div>
  <%= link_to "Back to searches", searches_path %>
</div>

app/views/searches/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @search %>

<div>
  <%= link_to "Edit this search", edit_search_path(@search) %> |
  <%= link_to "Back to searches", searches_path %>

  <%= button_to "Destroy this search", @search, method: :delete %>
</div>